### ISSUE TITLE
TreeViewItem missing in API docs?

### ISSUE THREAD

**Issue by yaustar** [playcanvas/pcui#117]

**Comment by willeastcott** [comment]
What you were originally pointing out was that there wasn't a Storybook entry for `TreeViewItem`. However, it doesn't really make sense to have such a page because you need a `TreeView` to visualize `TreeViewItem`s.

But you're asking about API reference. And now, you can find this here:

https://playcanvas.github.io/pcui/typedocs/classes/TreeViewItem-1.html

Fixed by #190.
