### ISSUE TITLE
Migrate ES6 components to TypeScript

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/pcui#189]
Benefits:

* All the well-established benefits of TS over JS.
* We'd get high quality TS declarations for free.
* The Storybook docs build process would presumably no longer require the JSDoc AST JSON generation step that is very brittle.

**Comment by kungfooman** [comment]
Please allow me to be a devils advocat here:

> * All the well-established benefits of TS over JS.

There are clearly downsides aswell, one of them is the absolute requirement of the complete build chain and we are speaking about 489 MB over 57650 files:

![image](https://user-images.githubusercontent.com/5236548/203029094-b174bc40-2ee1-438e-a047-e3d7da8f3cbe.png)

Right now it's not so complicated to treat PCUI like a JS module, just the same way you made it work for `playcanvas/engine`. PCUI just requires using an import map aswell:

```html
    <script type="importmap">
      {
        "imports": {
          "playcanvas": "http://127.0.0.1/playcanvas-engine/build/playcanvas.dbg.mjs/index.js",
          "pcui": "http://127.0.0.1/pcui-linux/src/index-importmap.js",
          "@playcanvas/observer": "http://127.0.0.1/playcanvas-observer/index.js",
          "playcanvas/build/playcanvas.mjs/math/curve-set.js": "http://127.0.0.1/playcanvas-engine/build/playcanvas.dbg.mjs/core/math/curve-set.js",
          "playcanvas/build/playcanvas.mjs/math/curve.js": "http://127.0.0.1/playcanvas-engine/build/playcanvas.dbg.mjs/core/math/curve.js",
          "playcanvas/build/playcanvas.mjs/math/math.js": "http://127.0.0.1/playcanvas-engine/build/playcanvas.dbg.mjs/core/math/math.js",
          "/pcui-linux/src/scss/themes/green/style.scss": "http://127.0.0.1/pcui-linux/dist/module/src/scss/themes/green/style.mjs"
        }
      }
    </script>
```

(this only works with absolute paths like `import 'Element/index.js'`, which are not present, I just added it locally)

The only ugly thing is `style.scss`, but that is the current "punishment" for disrespecting "Separation of Concerns" (SoC: don't mingle code with style). I would prefer a simple `pcui.css`, build from the `*.scss` - files.

Then in every script (without any build steps) you can simply write:

```js
import * as pcui from 'pcui';
import { Container } from 'pcui';
// Both valid, depending on your taste:
// use pcui.Container or Container
```

> * We'd get high quality TS declarations for free.

I worked out the PR to improve iirc nearly every constructor and added missing properties aswell, something you don't need TS for, especially if the code base is still using `: any` and `@ts-ignore`.

I feel that code becomes overly complicated without any apparent reason, simply because "one can". I would rather go the opposite way, "decomplicate" / decreasing complexity, sticking to KISS and SoC.

An example of that can also be found in e.g. `rollup.js`:

```js
const configs = [umd, module, react_umd, react_module]
    .map(conf => [conf(true), conf(false)])
    .reduce((configs, configPair) => [...configs, configPair[0], configPair[1]], []);
```

When I first saw that I was wondering what this is doing until I realized it's just flattening the array. If that would have been written in TypeScript, the mingled types themselves would "extra-blind" the developer. So looking at TS code often feels more obfuscating than "solving" to me, so it can decrease the developing experience aswell.

In the case above one can just write:

```js
const configs = [umd, module, react_umd, react_module]
    .map(conf => [conf(true), conf(false)])
    .flat();
```

Or ever shorter:

```js
const configs = [umd, module, react_umd, react_module]
    .flatMap(conf => [conf(true), conf(false)]);
```

This looks still comprehensible for JavaScript, while looking at TypeScript I often can't even see the "real" code (that actually does something) anymore (without "trying hard" to ignore TS). At the same time I love having type information, but "non-interfering" with the actual code in easy-to-ignore JSDoc comments.
