### ISSUE TITLE
Build fails on Node v15+

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/pcui#74]
A clean build fails on Node v15+, because `node-sass` package is not supported on it:
https://github.com/sass/node-sass/releases/tag/v4.14.1

**Comment by willeastcott** [comment]
I'm not sure this is a bug, per se. The Node.js site recommends most people stick to 14.x for now. Do you have any suggestions about how you would like this to be addressed?

**Comment by LeXXik** [comment]
Right, this is not a bug, but a compatability issue. One option is to add a description that the build is limited to Node v14. Another option could be to up the dependencies. For example, the problematic `node-sass` supports Node v15 in its latest v5.0.0 release:
https://github.com/sass/node-sass/releases/tag/v5.0.0
But that means there are some breaking changes, and might have some impact on other modules, which would also need to be updated. I will test it later.

**Comment by kungfooman** [comment]
`node-sass` is installed because `sass-loader` depends on it, yet it does not need to and the `sass-loader` people suggest `sass`:

https://www.npmjs.com/package/sass-loader

![image](https://user-images.githubusercontent.com/5236548/107119482-232e2600-6888-11eb-8247-f6540cdf89c1.png)

Therefore I would just uninstall `node-sass`, especially because it's a C/C++ monster using up like 260MB (Visual Studio Build, Python installation and only god knows what else), while `sass` package is exactly 5 files:

![image](https://user-images.githubusercontent.com/5236548/107119556-b5cec500-6888-11eb-8aae-4459ce6cc10e.png)


```
npm uninstall node-sass
npm install sass
```

But I just tested that and `webpack` seems unable to deal with that:

![image](https://user-images.githubusercontent.com/5236548/107119579-e0b91900-6888-11eb-98f8-ee46c927c86a.png)

While `rollup` has no problems with it:

![image](https://user-images.githubusercontent.com/5236548/107119595-ffb7ab00-6888-11eb-8679-3209f612c33b.png)

**Comment by LeXXik** [comment]
Speaking of which, building PCUI feels like installing an operating system :) 70k files and 200+ Mb takes forever. I didn't want to open a new issue on this, but at some point the dependencies requirements should be reviewed.

**Comment by willeastcott** [comment]
I had a go at upgrading all the NPM dependencies and I get:

![image](https://user-images.githubusercontent.com/697563/107144327-66dd6a00-6932-11eb-920a-7f13c8b64a49.png)

**Comment by kungfooman** [comment]
Did you do `npm update --force`? A normal `npm update` failed for me:

![image](https://user-images.githubusercontent.com/5236548/107196732-46c1af80-69f3-11eb-836f-9586a4ef7408.png)

Did you switch `node-sass` with `sass`? I did `npm update --force` (had sass replaced yesterday already) and everything works with node v15 here.
